### ISSUE TITLE
Error with the connection

### ISSUE THREAD

**Issue by Garicore01** [staze0/openctiXqradar#1]
When I do 
"python3 OpenCTI_QRadar.py -d 2"
I received this.
Traceback (most recent call last):
  File "/home/garellano/Documentos/qradar/openctiXqradar/OpenCTI_QRadar.py", line 510, in <module>
    main(ndays=program_args.ndays)
  File "/home/garellano/Documentos/qradar/openctiXqradar/OpenCTI_QRadar.py", line 463, in main
    get_OpenCTI_IPv4_execution, OpenCTI_IPs = get_OpenCTI_IPv4(filters = variables.default_query_filter.format(date_last_ndays))
  File "/home/garellano/Documentos/qradar/openctiXqradar/OpenCTI_QRadar.py", line 131, in get_OpenCTI_IPv4
    pprint(""" Number of IPv4 retrieve : {0} """.format(OpenCTI_request_globalCount).center(100, '-'), "DEBUG")
UnboundLocalError: local variable 'OpenCTI_request_globalCount' referenced before assignment

**Comment by Garicore01** [comment]
The problem is the GraphQL Query. 
{"errors":[{"message":"Expected value of type \"FilterGroup\", found [{filterMode: and, values: \"2024-06-25\", operator: \"gt\", key: created_at}].","locations":[{"line":7,"column":14}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"edges\" on type \"Label\".","locations":[{"line":35,"column":11}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}
